### ISSUE TITLE
This is illegal decompilation, not FOSS

### ISSUE THREAD

**Issue by KAMiKAZOW** [flathub/com.github.k4zmu2a.spacecadetpinball#12]
Upstream repository says "**Decompilation** of 3D Pinball for Windows – Space Cadet". It's also using the original, copyrighted graphics.

The attached MIT license is not valid unless the original Space Cadet author released the source code under MIT license or gave permission to reverse engineer the code.

This is a derivative work of copyrighted software.

**Comment by kowalski7cc** [comment]
Hello @KAMiKAZOW, the assets are not included in the flatpak packages (nor in the upstream repository), but are downloaded from archive.org on install time, unzipped and copied in the correct folders (Like it's done in the AUR counterpart).
We can talk tho about the binary, that yes it comes from the original decompiled binary, but has been rewritten to use SDL2 so I think it kinda lands on a gray area. Also we are talking of a 20 years old game...
@k4zmu2a

**Comment by KAMiKAZOW** [comment]
Derivative work is derivative work. That's not really a grey area. That's like saying that taking Harry Potter, running the entire book through an automated translator, then manually cleaning up the bad grammar, and publishing the result would be a grey area.

Quick look at Wikipedia says that it's a version of a Maxis game, so EA holds the rights. Flathub shouldn't distribute pirated software.

**Comment by kowalski7cc** [comment]
@hfiguiere
A workaround could be to remove the binary from flathub and just distribute the postinstall script :thinking:

**Comment by hfiguiere** [comment]
@barthalion can take down this package if needed.

**Comment by KAMiKAZOW** [comment]
> A workaround could be to remove the binary from flathub and just distribute the postinstall script 🤔

If that's a valid workaround for the Flathub organization, I'm waiting for submissions of cracked Adobe CC apps. Could download the torrents via postinstall scripts as well. Perhaps also individual submissions for Nintendo ROMs. Nintendo is very relaxed about that matter, I hear....

Seriously, though: Upstream does not even claim that this is a clean room reimplementation of the engine. They outright say it's a decompilation project. This is clear cut.

**Comment by barthalion** [comment]
Unless @KAMiKAZOW is copyright holder of Space Cadet, there's nothing to discuss here. Feel free to exercise copyright violation with Internet Archive first. We don't distribute anything illegal.

**Comment by barthalion** [comment]
Similarly, if you're unhappy about it being a decompilation, contacting GitHub is your best shot.

**Comment by barthalion** [comment]
And on that note, copyright matters should be e-mailed to flathub@lists.freedesktop.org, not reported at random places. I think this exhausts the discussion here.

**Comment by KAMiKAZOW** [comment]
I wasn't aware the actual bug tracker counts as random place. I was merely trying to be helpful before EA or Microsoft come at Flathub. Sorry for the inconvenience.
