### ISSUE TITLE
Bad path on archive.org after site reorg

### ISSUE THREAD

**Issue by WrongProblem** [flathub/com.github.k4zmu2a.spacecadetpinball#31]
Hello

following the archive.org problem, flatpak can't find the file at

https://github.com/flathub/com.github.k4zmu2a.spacecadetpinball/blob/88284139b27b96c8d21305aba134f8841a7b398f/com.github.k4zmu2a.spacecadetpinball.yml#L80

wget https://archive.org/26/items/pinball_202007/Pinball.zip

returns html error page instead of the desired zip file.

The old URL could be replaced by the following working one:

https://archive.org/download/pinball_202007/Pinball.zip

**Comment by kowalski7cc** [comment]
Yeah, probably the bot did wrong when Archive was offline, will fix asap

**Comment by WrongProblem** [comment]
@kowalski7cc 

well, the bot detected that the html message error code replaced the original file and dutifully did its job by downloading it in https://github.com/flathub/com.github.k4zmu2a.spacecadetpinball/pull/30/commits/9a694386b6c74b5581728df19ced700596be6fc4

![image](https://github.com/user-attachments/assets/946b8634-3d74-4514-a330-215da4e10782)

**Comment by kowalski7cc** [comment]
Fixed in #32, should be online in few hours
